#' Get obj for module building:
#' check groups # be sure the two set have same groups.
#' check variables: use the intersect vars by default.
#' clean the var names(remove the blank and other codes)
#' when the var wasn't started with letters, the head will be added.
#' generate formulas
#' @param sig_v sig variables, character vector.
#' @param train_set ExperimentSet S4 generated by Train data.
#' @param test_set ExperimentSet S4 generated by
#' @examples
#' \dontrun{
#' train_set = ExpressionSet_train ##
#' test_set  = ExpressionSet_test
#' sig_v = c("L_Aspartic acid", "L_Serine","9987","_ddd dkkj")
#' get_module_data(train_set = ExpressionSet_train,
#'                 test_set = ExpressionSet_test,
#'                 sig_v = c("L_Aspartic acid", "L_Serine","9987","_ddd dkkj"))
#'
#' }
#' @return a list with data and formula for moduling.
#' @export
get_module_data <- function(train_set, test_set, sig_v){
    module_data <- list() ## for output
    module_data$train <- get_ls_for_model(set = train_set)
    module_data$test  <- get_ls_for_model(set = test_set)
    module_data$train_note <- train_set@experimentData@title
    module_data$test_note  <-  test_set@experimentData@title

    sig_v <-  sig_v %>% process_var_Name(input_name = .)
    module_data$final_sig_v <- intersect(module_data$train %>% colnames(), module_data$test %>% colnames()) %>% intersect(.,sig_v)
    ### 最后生成formula即可。
    module_data$my_formula  <- module_data$final_sig_v %>%
        paste0(., collapse = "+") %>%
        paste0("group ~  ", .) %>% as.formula()
    return(module_data)
}



#' Turn the ExperimentSet S4 into a data frame
#' @param set train_set or test_set, ExperimentSet. process and get the new dat for module.
#' @return a dataframe with "group" and other var.
#'
get_ls_for_model <- function(set){
    set@assayData$exprs
    dat <- set@assayData$exprs %>% t %>% data.frame(., stringsAsFactors = T, check.names = F)
    # group_levels <- set$ClassNote %>% unique %>% sort
    group_v <- rownames(dat) %>% match(., set@phenoData@data$SampleID) %>% set@phenoData@data$ClassNote[.]
    dat[,"group"] <- group_v %>% factor(., labels = 0:1) %>% as.character() %>% as.numeric(.)

    ## factor 的level在未指定时，会自动进行排序。
    dat %>% head
    colnames(dat) <-  dat %>% colnames %>% process_var_Name(input_name = .)
    return(dat)
}

#' process_Name for module.
#' 清洗变量名
#' replace and remove sth to ensure the var name can be used correctly in a formular
#' @param input_name name vector :to be cleaned.
#' @param var_head the head for variable which wasn't started with letters.
#' @examples
#' \dontrun{
#' input_name <- c("L_Aspartic acid", "L_Serine","9987","_ddd dkkj")
#' process_var_Name(input_name = input_name)
#' }
#' @export
process_var_Name <- function(input_name, var_head = "V"){
    head <- paste0(var_head, "\\1")
    input_name %>% gsub("[-*+ ().,;]","_",.) %>% gsub("(^[^a-zA-Z])",head,.)
}
# input_name <- c("L_Aspartic acid", "L_Serine","9987","_ddd dkkj")
# process_var_Name(input_name = input_name)
